### ISSUE TITLE
[develop] branch fails to render pillars when used with salt 2018.3

### ISSUE THREAD

**Issue by epcim** [salt-formulas/reclass#27]
Reported in upstream https://github.com/saltstack/salt/issues/47126

**Comment by bbinet** [comment]
@epcim Do you know a workaround to have reclass work with salt 2018.3 ?

Do you think it will work with upcoming salt version 2018.3.1 ?

**Comment by epcim** [comment]
I hope so, but not yet tested. We should push on Saltstack to come with some proper fix in upstream, we are not only one affected 3rd party extension.

**Comment by bbinet** [comment]
Ok.

**Comment by max-arnold** [comment]
I made a fork of `reclass` which fixes this issue https://github.com/max-arnold/reclass/commits/maintenance and also ported reclass to Python 2.7/3.6.  This fix took less time than migration attempt to built-in `saltclass`.

Briefly tested this with Salt 2018.3.1, Python2.7/Python3.6 and existing reclass tree (~300 classes, ~70 nodes). Any feedback/bugs are appreciated.

**Comment by epcim** [comment]
Thanks, I will definitively have a look.

**Comment by epcim** [comment]
I checked it works with 2018.3.1, will be released in v1.5.4
