### ISSUE TITLE
Duplicate namespaces for internal parameters?

### ISSUE THREAD

**Issue by max-arnold** [salt-formulas/reclass#82]
While running `salt-call --local --id example.com pillar.data` I noticed that there are two similar looking internal `__reclass__` parameter namespaces:

```
    __reclass__:
        ----------
        applications:
        classes:
        environment:
            base
        nodename:
            example.com
    _reclass_:
        ----------
        environment:
            base
        name:
            ----------
            full:
                example.com
            short:
                example
```

The first one is double-underscore `__reclass__`, and the second one is single-underscore `_reclass_`. I believe this was added in https://github.com/salt-formulas/reclass/commit/7aea78d743f9ecb56beaf1489896596b28f008a2

Is the second one a typo? It seems redundant (at least the `environment` key and full node name are duplicate).

**Comment by AndrewPickford** [comment]
There's a subtle difference. The double underscore __reclass__ key that appears in the pillar data passed to salt is added in as part of the salt-reclass adapter after the normal reclass processing which means you cannot use it during the reclass run as a reference.  The _reclass_ single underscore parameters are put in as parameters as part of the merge so a reference like ${_reclass_:name:full} will resolve correctly.  I don't think this is documented so I may be the only one using the single underscore _reclass_ parameters.

**Comment by max-arnold** [comment]
@AndrewPickford Thank you for the clarification.
